FROM postgres:17

# Copiar scripts de inicialización
# COPY Tests/init-scripts/ /docker-entrypoint-initdb.d/

# Variables de entorno por defecto
ENV POSTGRES_DB=ladevi_ventas_test
ENV POSTGRES_USER=sa
ENV POSTGRES_PASSWORD=password
ENV POSTGRES_HOST=ladevi_ventas_api_pg_db_testing

# Los scripts se ejecutarán automáticamente en orden alfabético:
# 01-schema.sql (esquema)
# 02-basic-data.sql (datos básicos)