@base_url = https://xubio.com:443/API/1.1
# @clientId = 610878458668984820993609961633570808727826981097832302948251272627992419493371458668610878497337325707
# @secretId = 9Ltn8CP+0/Q-j1kCmlttMHdj72vmAaGunDoE10fOB/i6=k9qQInnwbtewQAeUFhxMECnhKl*NzzzU2jl=GPVV7Tl9ONF6qBp5xMCw-W1i9Ltn8CP+0/Q-j1kCmlttMHdj72

@clientId = 64968109892398023422332550029692555540272157308187024975502141169607192375530098923649681517186341372
@secretId = RgKl=5Lo5eLaKXweDcCM4qJs*eQhcwzOa91nXr5j0yFgiEjAIeq6niCw-YLf30/QZO4btGWm=B40agRo*m=wERpqI=CFcKfpVLDJcL_CPRgKl=5Lo5eLaKXweDcCM4qJs*

### Auth
POST {{base_url}}/TokenEndpoint
Content-Type: application/x-www-form-urlencoded
Authorization: Basic {{clientId}}:{{secretId}}

grant_type=client_credentials

### reemplazar con lo que arriba se retorne
@access_token=QV04iA_0UVmT77ScteufHQp/9qSWmD35A5_Y+UyjlbV_cnlrXr4-36K-/Fh09A0Ub_C+EL8EYsIX8bi3HhGN9Cfc95KIRmVSE7s+vtAzaQ/31LEA/wrgC=/9uu+zNQV04iA_0UVmT77ScteufHQp/9

###
GET {{base_url}}/circuitoContableBean?activo=1
Authorization: Bearer {{access_token}}
Content-Type: application/json

###
GET {{base_url}}/clienteBean?activo=1
Authorization: Bearer {{access_token}}
Content-Type: application/json

###
GET {{base_url}}/puntoVentaBean?activo=1
Authorization: Bearer {{access_token}}
Content-Type: application/json

###
GET {{base_url}}/monedaBean?activo=1
Authorization: Bearer {{access_token}}
Content-Type: application/json

###
GET {{base_url}}/ProductoVentaBean?activo=1
Authorization: Bearer {{access_token}}
accept: application/json
Content-Type: application/json

###
GET {{base_url}}/monedaBean?activo=1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{access_token}}

### Facturar
POST {{base_url}}/facturar
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "tipo": 1,
  "cliente": {
    "ID": 7955443,
    "id": 7955443
  },
  "puntoVenta": {
    "codigo": "DEFAULT",
  },
  "fecha": "2025-05-09",
  "condicionDePago": 2,
  "moneda": {
    "codigo": "PESOS_ARGENTINOS",
  },
  "descripcion": "Descripción de prueba",
  "transaccionProductoItems": [
    {
      "producto": {
        "codigo": "PRODUCTO_AL_21",
      },
      "descripcion": "Descripción de prueba prod",
      "cantidad": 1,
      "precio": 10
    }
  ]
}

### Facturar
POST {{base_url}}/comprobanteVentaBean
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "tipo": 1,
  "cliente": {
    "ID": 7955443,
    "id": 7955443
  },
  "puntoVenta": {
    "codigo": "PV1",
  },
  "fecha": "2025-05-09",
  "condicionDePago": 2,
  "moneda": {
    "codigo": "PESOS_ARGENTINOS",
  },
  "descripcion": "Descripción de prueba",
  "transaccionProductoItems": [
    {
      "producto": {
        "codigo": "PRODUCTO_AL_21",
      },
      "descripcion": "Descripción de prueba prod",
      "cantidad": 2,
      "precio": 10
    }
  ]
}

### Paises
GET {{base_url}}/paisBean?activo=1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{access_token}}




