@base_url = https://xubio.com:443/API/1.1
@clientId = 155988453352984340054796562566906948273684510856420265028011292958656683196584453352155988496698299177
@secretId = n02Qg/VnQx0KKqrpCxlNuGxaN1D0Fx5v6or1D080Y8U9/bxLED3_dz*3tJ0BGIfleso+l09AuZQOUUg/OjnCai7sWvwY91k01=8i95V0n02Qg/VnQx0KKqrpCxlNuGxaN1
@authBase64= MTU1OTg4NDUzMzUyOTg0MzQwMDU0Nzk2NTYyNTY2OTA2OTQ4MjczNjg0NTEwODU2NDIwMjY1MDI4MDExMjkyOTU4NjU2NjgzMTk2NTg0NDUzMzUyMTU1OTg4NDk2Njk4Mjk5MTc3Om4wMlFnL1ZuUXgwS0txcnBDeGxOdUd4YU4xRDBGeDV2Nm9yMUQwODBZOFU5L2J4TEVEM19keiozdEowQkdJZmxlc28rbDA5QXVaUU9VVWcvT2puQ2FpN3NXdndZOTFrMDE9OGk5NVYwbjAyUWcvVm5ReDBLS3FycEN4bE51R3hhTjE=

### Auth
POST {{base_url}}/TokenEndpoint
Content-Type: application/x-www-form-urlencoded
Authorization: Basic {{clientId}}:{{secretId}}

grant_type=client_credentials

### reemplazar con lo que arriba se retorne
@access_token=onQznPnZ9dHYro+xHezkvP9Jb8YatVPFb6Lf4EcJcjPKuLcA5asOpf2uceaH5P4mnlhRxc0zLCe=dA25xEYqdTD-LIrnNXEZuEJunHliO_Ps9d9xTK9Wbw64ZmGXtonQznPnZ9dHYro+xHezkvP9Jb

###
GET {{base_url}}/circuitoContableBean?activo=1
Authorization: Bearer {{access_token}}
Content-Type: application/json

###
GET {{base_url}}/clienteBean?activo=1
Authorization: Bearer {{access_token}}
Content-Type: application/json

###
GET {{base_url}}/puntoVentaBean?activo=1
Authorization: Bearer {{access_token}}
Content-Type: application/json

###
GET {{base_url}}/monedaBean?activo=1
Authorization: Bearer {{access_token}}
Content-Type: application/json

###
GET {{base_url}}/ProductoVentaBean?activo=1
Authorization: Bearer {{access_token}}
accept: application/json
Content-Type: application/json

###
GET {{base_url}}/monedaBean?activo=1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{access_token}}

### Facturar
POST {{base_url}}/facturar
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "tipo": 1,
  "cliente": {
    "ID": 7955443,
    "id": 7955443
  },
  "puntoVenta": {
    "codigo": "DEFAULT",
  },
  "fecha": "2025-05-09",
  "condicionDePago": 2,
  "moneda": {
    "codigo": "PESOS_ARGENTINOS",
  },
  "descripcion": "Descripción de prueba",
  "transaccionProductoItems": [
    {
      "producto": {
        "codigo": "PRODUCTO_AL_21",
      },
      "descripcion": "Descripción de prueba prod",
      "cantidad": 1,
      "precio": 10
    }
  ]
}

### Facturar
POST {{base_url}}/comprobanteVentaBean
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "tipo": 1,
  "cliente": {
    "ID": 7955443,
    "id": 7955443
  },
  "puntoVenta": {
    "codigo": "PV1",
  },
  "fecha": "2025-05-09",
  "condicionDePago": 2,
  "moneda": {
    "codigo": "PESOS_ARGENTINOS",
  },
  "descripcion": "Descripción de prueba",
  "transaccionProductoItems": [
    {
      "producto": {
        "codigo": "PRODUCTO_AL_21",
      },
      "descripcion": "Descripción de prueba prod",
      "cantidad": 2,
      "precio": 10
    }
  ]
}



