@base_url = https://xubio.com:443/API/1.1
@clientId = 610878458668984820993609961633570808727826981097832302948251272627992419493371458668610878497337325707
@secretId = 9Ltn8CP+0/Q-j1kCmlttMHdj72vmAaGunDoE10fOB/i6=k9qQInnwbtewQAeUFhxMECnhKl*NzzzU2jl=GPVV7Tl9ONF6qBp5xMCw-W1i9Ltn8CP+0/Q-j1kCmlttMHdj72

### Auth
POST {{base_url}}/TokenEndpoint
Content-Type: application/x-www-form-urlencoded
Authorization: Basic {{clientId}}:{{secretId}}

grant_type=client_credentials

### reemplazar con lo que arriba se retorne
@access_token=cekM4vykruJt2UBgiFxKBh9Z0A6lUNx/1CJEvIq+zOfHDqIeoedfVDNtDXf0vndS+teu5yOxf0ZhwCiCp741gY=d5PT7DhiRykqiUH0a*FfdRMP4d39gehvCD_FnucekM4vykruJt2UBgiFxKBh9Z0A

###
GET {{base_url}}/circuitoContableBean?activo=1
Authorization: Bearer {{access_token}}
Content-Type: application/json

###
GET {{base_url}}/clienteBean?activo=1
Authorization: Bearer {{access_token}}
Content-Type: application/json

###
GET {{base_url}}/puntoVentaBean?activo=1
Authorization: Bearer {{access_token}}
Content-Type: application/json

###
GET {{base_url}}/monedaBean?activo=1
Authorization: Bearer {{access_token}}
Content-Type: application/json

###
GET {{base_url}}/ProductoVentaBean?activo=1
Authorization: Bearer {{access_token}}
accept: application/json
Content-Type: application/json

###
GET {{base_url}}/monedaBean?activo=1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{access_token}}

### Facturar
POST {{base_url}}/facturar
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "tipo": 1,
  "cliente": {
    "ID": 7955443,
    "id": 7955443
  },
  "puntoVenta": {
    "codigo": "DEFAULT",
  },
  "fecha": "2025-05-09",
  "condicionDePago": 2,
  "moneda": {
    "codigo": "PESOS_ARGENTINOS",
  },
  "descripcion": "Descripción de prueba",
  "transaccionProductoItems": [
    {
      "producto": {
        "codigo": "PRODUCTO_AL_21",
      },
      "descripcion": "Descripción de prueba prod",
      "cantidad": 1,
      "precio": 10
    }
  ]
}

### Facturar
POST {{base_url}}/comprobanteVentaBean
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "tipo": 1,
  "cliente": {
    "ID": 7955443,
    "id": 7955443
  },
  "puntoVenta": {
    "codigo": "PV1",
  },
  "fecha": "2025-05-09",
  "condicionDePago": 2,
  "moneda": {
    "codigo": "PESOS_ARGENTINOS",
  },
  "descripcion": "Descripción de prueba",
  "transaccionProductoItems": [
    {
      "producto": {
        "codigo": "PRODUCTO_AL_21",
      },
      "descripcion": "Descripción de prueba prod",
      "cantidad": 2,
      "precio": 10
    }
  ]
}



